log_dir: "turkish_from_0_cont_newscrawl"
mixed_precision: "fp16"
data_folder: "data/tr/turkish_processed"
validation_folder: "data/tr/turkish_dev_processed"
batch_size: 40
save_interval: 5000
log_interval: 10
val_interval: 100
num_process: 1 # number of GPUs
num_steps: 9900000

dataset_params:
    tokenizer: "custom"
    token_separator: " " # token used for phoneme separator (space)
    token_mask: "M" # token used for phoneme mask (M)
    word_separator: 3039 # token used for word separator (<formula>)
    token_maps: "data/tr/token_maps_turkish.pkl" # token map path
    
    max_mel_length: 512 # max phoneme length
    
    word_mask_prob: 0.15 # probability to mask the entire word
    phoneme_mask_prob: 0.1 # probability to mask each phoneme
    replace_prob: 0.2 # probablity to replace phonemes
    
model_params:
    vocab_size: 178
    hidden_size: 768
    num_attention_heads: 12
    intermediate_size: 2048
    max_position_embeddings: 512
    num_hidden_layers: 12
    dropout: 0.1
